# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 32595c58f59c86163fc96f23542cac3d235de58dac2ece507a6b64bbca1e0d21c2cb8b29ea839ec2097bd049a7926ce4e46b2b69df06d5bcfd0e9cf13cb6074e

test:
  secret_key_base: 09b30d33d3bb5c82d400f372dba374ca06db0241a6cf6f4dcb036e5dd5a59374ce5d752f3f5258a8393dac8525776e44f34bc60a7e6d94a29781cc2b17d7ae75

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
